services:
  mrp-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: mrp-app
    restart: unless-stopped
    working_dir: /var/www/html/mrp
    volumes:
      - ./:/var/www/html/mrp
    networks:
      - mrp-network
    depends_on:
      - mrp-db

  mrp-web:
    image: nginx:alpine
    container_name: mrp-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/mrp
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mrp-network
    depends_on:
      - mrp-app

  mrp-db:
    image: mysql:8.0
    container_name: mrp-db
    restart: unless-stopped
    command: --sql-mode="NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_mrp
      MYSQL_USER: mrp_user
      MYSQL_PASSWORD: mrp_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mrp_dbdata:/var/lib/mysql
    networks:
      - mrp-network

  mrp-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mrp-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mrp-db
      PMA_USER: mrp_user
      PMA_PASSWORD: mrp_password
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - mrp-network
    depends_on:
      - mrp-db

networks:
  mrp-network:
    driver: bridge

volumes:
  mrp_dbdata:
